# TCL File Generated by Component Editor 11.1sp1
# Mon Apr 23 01:34:21 JST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | iic "I2C Master" v1.0
# | iseroid 2012.04.23.01:34:21
# | 
# | 
# | C:/ise_work/2012pov/trunk/prj/iic/iic_core.v
# | 
# |    ./iic_core.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module iic
# | 
set_module_property NAME iic
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR iseroid
set_module_property DISPLAY_NAME "I2C Master"
set_module_property TOP_LEVEL_HDL_FILE iic_core.v
set_module_property TOP_LEVEL_HDL_MODULE iic_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME iic_core
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file iic_core.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter S_IDLE STD_LOGIC_VECTOR 0
set_parameter_property S_IDLE DEFAULT_VALUE 0
set_parameter_property S_IDLE DISPLAY_NAME S_IDLE
set_parameter_property S_IDLE WIDTH 4
set_parameter_property S_IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property S_IDLE ENABLED false
set_parameter_property S_IDLE UNITS None
set_parameter_property S_IDLE ALLOWED_RANGES 0:15
set_parameter_property S_IDLE AFFECTS_GENERATION false
set_parameter_property S_IDLE HDL_PARAMETER true
add_parameter S_START STD_LOGIC_VECTOR 1
set_parameter_property S_START DEFAULT_VALUE 1
set_parameter_property S_START DISPLAY_NAME S_START
set_parameter_property S_START WIDTH 4
set_parameter_property S_START TYPE STD_LOGIC_VECTOR
set_parameter_property S_START ENABLED false
set_parameter_property S_START UNITS None
set_parameter_property S_START ALLOWED_RANGES 0:15
set_parameter_property S_START AFFECTS_GENERATION false
set_parameter_property S_START HDL_PARAMETER true
add_parameter S_WRITE STD_LOGIC_VECTOR 2
set_parameter_property S_WRITE DEFAULT_VALUE 2
set_parameter_property S_WRITE DISPLAY_NAME S_WRITE
set_parameter_property S_WRITE WIDTH 4
set_parameter_property S_WRITE TYPE STD_LOGIC_VECTOR
set_parameter_property S_WRITE ENABLED false
set_parameter_property S_WRITE UNITS None
set_parameter_property S_WRITE ALLOWED_RANGES 0:15
set_parameter_property S_WRITE AFFECTS_GENERATION false
set_parameter_property S_WRITE HDL_PARAMETER true
add_parameter S_READ STD_LOGIC_VECTOR 3
set_parameter_property S_READ DEFAULT_VALUE 3
set_parameter_property S_READ DISPLAY_NAME S_READ
set_parameter_property S_READ WIDTH 4
set_parameter_property S_READ TYPE STD_LOGIC_VECTOR
set_parameter_property S_READ ENABLED false
set_parameter_property S_READ UNITS None
set_parameter_property S_READ ALLOWED_RANGES 0:15
set_parameter_property S_READ AFFECTS_GENERATION false
set_parameter_property S_READ HDL_PARAMETER true
add_parameter S_STOP STD_LOGIC_VECTOR 4
set_parameter_property S_STOP DEFAULT_VALUE 4
set_parameter_property S_STOP DISPLAY_NAME S_STOP
set_parameter_property S_STOP WIDTH 4
set_parameter_property S_STOP TYPE STD_LOGIC_VECTOR
set_parameter_property S_STOP ENABLED false
set_parameter_property S_STOP UNITS None
set_parameter_property S_STOP ALLOWED_RANGES 0:15
set_parameter_property S_STOP AFFECTS_GENERATION false
set_parameter_property S_STOP HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 16
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave address address Input 4
add_interface_port avalon_slave chipselect chipselect Input 1
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point iic_signals
# | 
add_interface iic_signals conduit end

set_interface_property iic_signals ENABLED true

add_interface_port iic_signals scl_out export Output 1
add_interface_port iic_signals scl_in export Input 1
add_interface_port iic_signals sda_out export Output 1
add_interface_port iic_signals sda_in export Input 1
# | 
# +-----------------------------------
